### PR TITLE
Add support for exists operator in query conditions

### PR DESCRIPTION
**Pull request by mdsiddiq-till**
## Description

Add support for exists operator in query conditions
https://www.loom.com/share/cd67a17f0426425eac578d496006bb7b
## Related Issues

Issue: #112 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by snehithv — DISMISSED** [review]

**Review by NalinSajwan — DISMISSED** [review]
Nice work!! 👍

**Comment by mdsiddiq-till** [comment]
@snehithv @NalinSajwan Added tests to cover new changes.

**Review by snehithv — APPROVED** [review]

**Comment by mdsiddiq-till** [comment]
We need to force merge this pr.
The check for codecov/project is not working it seems.

**Comment by lakshmaji-till** [comment]
I have a doubt here. When the expected filter expr attributes will be unavalilable

**Review by lakshmaji-till — APPROVED** [review]

**Comment by mdsiddiq-till** [comment]
> I have a doubt here. When the expected filter expr attributes will be unavalilable

Cleared on the call.

**Review by snehithv — APPROVED** [review]

**Pull request merged**
